### ISSUE TITLE
[Feature] Increase transparency using checkboxes & disclaimers

### ISSUE THREAD

**Issue by MeikeMolitor** [deltaDAO/mvg-portal#177]
## Motivation / Problem
There is potential to increase transparency towards our users regarding the immutability of blockchains.

## Solution
(1) When publishing a service offering we can introduce (two) checkboxes next to the "SUBMIT" button which must be selected before the service offering can be published. Suggested text:
- I agree that my wallet address and public key will be transmitted to a smart contract stored permanently on the Gaia-X testnet, so I can prove service offering ownership and sales.
- I confirm that I did not provide personal data in the metadata, which will be stored permanently on-chain on the Gaia-X testnet.

(2) When consuming a service offering, we can add a disclaimer below the "BUY COMPUTE JOB" / "GET"button. Suggested text:
If you consume a service offering, your wallet address and public key will be stored permanently on-chain on the Gaia-X testnet. For more information, please refer to our [privacy policy](https://portal.minimal-gaia-x.eu/privacy/en).

## Alternatives
Instead of checkboxes we could also add an additional disclaimer.

--- 
**Tasks:**
- [x] Add required checkbox at end of publishing form: ```I agree that my wallet address and public key will be transmitted to a smart contract stored permanently on the Gaia-X testnet, so I can prove service offering ownership and sales.```
- [x] Add required checkbox at end of publishing form: ```I confirm that I did not provide personal data in the metadata, which will be stored permanently on-chain on the Gaia-X testnet.```
- [x] Add disclaimer in `<ButtonBuy>` component, below the button itself: ```
If you consume a service offering, your wallet address and public key will be stored permanently on-chain on the Gaia-X testnet. For more information, please refer to our [privacy policy](https://portal.minimal-gaia-x.eu/privacy/en).```

**Comment by LucaMilanese90** [comment]
@moritzkirstein @oceanByte how do we want to structure the new checkboxes in the ddo? Currently, we have a `termsAndConditions` key, but it's not in use and it defaults to `false`.

I see 3 options:
- add some new keys representing the new values on the current `termsAndConditions` level
- transform the `termsAndConditions` key into an object that will contain all the other confirmations
- combine the two new checkboxes and register a single boolean for `termsAndConditions`

Unless we are making some specific use of these values, I would go with number 3, considering the fact we only allow pubblish if all the conditions are met.

**Comment by moritzkirstein** [comment]
We do need `termsAndConditions` eventually, so would not touch this at this point in time.
I think we should add a new property in the DDO:
```tsx
consent: {
  walletAddress: true,
  noPersonalData: true
}
```
Only allow publishing of the DDO out of our market if both of these are checked/true.
We should therefore not have any DDOs published out of our MVG that do not have a consent object with false values.
We can later think about moving `termsAndConditions` into this object as well, but this is out of scope and a decision for later.

CC @MeikeMolitor here to approve this approach
